"""empty message

Revision ID: 39e5898161df
Revises: cd297d954f72
Create Date: 2017-11-19 15:15:49.620134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39e5898161df'
down_revision = 'cd297d954f72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
