"""empty message

Revision ID: e2ca394f0479
Revises: e334522f6433
Create Date: 2017-11-19 13:17:01.542957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2ca394f0479'
down_revision = 'e334522f6433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birthdate', sa.String(length=200), nullable=False))
    op.add_column('user', sa.Column('name', sa.String(length=200), nullable=False))
    op.drop_column('user', 'login')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('user', 'name')
    op.drop_column('user', 'birthdate')
    # ### end Alembic commands ###
