"""empty message

Revision ID: e334522f6433
Revises: 90d7d6f11137
Create Date: 2017-11-19 13:11:53.431654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e334522f6433'
down_revision = '90d7d6f11137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=True))
    op.execute('UPDATE "user" SET role_id=1')
    op.alter_column('user', 'role_id', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role_id')
    # ### end Alembic commands ###
