"""empty message

Revision ID: fada843444de
Revises: e2ca394f0479
Create Date: 2017-11-19 13:42:06.215829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fada843444de'
down_revision = 'e2ca394f0479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password', type_=sa.String(256), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
